### ISSUE TITLE
Writes to Snowflake are happening every 60 seconds approx. despite increasing buffer time and checkpointing interval

### ISSUE THREAD

**Issue by vinclv** [deltastreaminc/flink-connector-snowflake#44]
Hi Team,
I am using the SF connector for sinking records from S3. My flink application has a checkpointing interval of 5 minutes.  As per the flink documentation, below is what I see about bufferTimeMillis

_bufferTimeMillis is the time in milliseconds to buffer records before writing them to Snowflake. NOTE: The buffer is also flushed when a checkpoint is triggered or the job is stopped._

I set the buffer time to a very large value to enable the connector to perform flush only during checkpointing as below

```
SnowflakeSink.<Event>builder()
                .url(snowflakePrope.get("SNOWFLAKE_ACCOUNT"))
                .bufferTimeMillis(2678400000L)
                .build("Snowflake Sink")
```
              
With this, I expected the flush to happen only every 5 mins. But, I noticed the writes to Snowflake table approx. every 60 seconds. [The delta stream page about this connector](https://www.deltastream.io/open-sourcing-our-snowflake-connector-for-apache-flink/) also tells only about checkpointing and buffertime when it comes to flushing as below

_In this example, the checkpointing interval is set to 100 milliseconds, and the buffering interval is configured as 1 second.  This tells the Flink job to flush the records at least every 100 milliseconds, i.e., on every checkpoint._

Could you please let me know the reason behind this behavior?

Thanks

**Comment by mohsenrezaeithe** [comment]
Hey @vinclv, buffer time and checkpoint are the only configurable max limits that can be set using the connector APIs today, and without knowing the details of your job, I can't say what's actually contributing to "early" writes/flush.

However, the `MAX_CHUNKS_IN_BLOB` parameter with a max of 100 rows could be what you're running into. This parameter is not configurable today, but will be available for all created channels.

It'd be interesting to see if there are any logs showing what's triggering the flush in the background.

**Comment by vinclv** [comment]
Hi @mohsenrezaeithe 
thanks for your response and sorry for coming very late. I tried to mitigate the above issue using the logic that flush should happen only via CHECKPOINT time by increasing the Buffer interval for flush and since then, all looks good.

Also, I would like to check if you have any expected timeline for making the connector exactly once? 

Thanks in advance.

**Comment by vinclv** [comment]
Hi @mohsenrezaeithe 
thanks for your response and sorry for coming very late. I tried to mitigate the above issue using the logic that flush should happen only via CHECKPOINT time by increasing the Buffer interval for flush and since then, all looks good.

Also, I would like to check if you have any expected timeline for making the connector exactly once? I am asking this because, I noticed an issue that happened all of a sudden in the running application as below

`java.lang.RuntimeException: org.apache.flink.shaded.net.snowflake.ingest.utils.SFException: Channel SNOWFLAKE SINK_12 is invalid and might contain uncommitted rows, please consider reopening the channel to restart.
        at io.deltastream.flink.connector.snowflake.sink.internal.SnowflakeSinkServiceImpl.ingestionFallbackSupplier(SnowflakeSinkServiceImpl.java:325)
        at io.deltastream.flink.connector.snowflake.sink.internal.SnowflakeSinkServiceImpl.lambda$insertRowWithFallback$1(SnowflakeSinkServiceImpl.java:295)
        at org.apache.flink.shaded.dev.failsafe.Functions.lambda$toFn$16(Functions.java:281)
        at org.apache.flink.shaded.dev.failsafe.internal.FallbackImpl.apply(FallbackImpl.java:58)
        at org.apache.flink.shaded.dev.failsafe.internal.FallbackExecutor.lambda$apply$0(FallbackExecutor.java:62)
        at org.apache.flink.shaded.dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187)
        at org.apache.flink.shaded.dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
        at org.apache.flink.shaded.dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:112)
        at io.deltastream.flink.connector.snowflake.sink.internal.SnowflakeSinkServiceImpl.insertRowWithFallback(SnowflakeSinkServiceImpl.java:313)
        at io.deltastream.flink.connector.snowflake.sink.internal.SnowflakeSinkServiceImpl.insert(SnowflakeSinkServiceImpl.java:141)
        at io.deltastream.flink.connector.snowflake.sink.SnowflakeSinkWriter.write(SnowflakeSinkWriter.java:118)
        at org.apache.flink.streaming.runtime.operators.sink.SinkWriterOperator.processElement(SinkWriterOperator.java:160)
        at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask$StreamTaskNetworkOutput.emitRecord(OneInputStreamTask.java:238)
        at org.apache.flink.streaming.runtime.io.AbstractStreamTaskNetworkInput.processElement(AbstractStreamTaskNetworkInput.java:157)
        at org.apache.flink.streaming.runtime.io.AbstractStreamTaskNetworkInput.emitNext(AbstractStreamTaskNetworkInput.java:114)
        at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:65)
        at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:579)
        at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:231)
        at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:909)
        at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:858)
        at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:960)
        at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:939)
        at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:753)
        at org.apache.flink.runtime.taskmanager.Task.run(Task.java:568)
        at java.base/java.lang.Thread.run(Thread.java:829)
        Suppressed: org.apache.flink.shaded.net.snowflake.ingest.utils.SFException: Channel SNOWFLAKE SINK_12 is invalid and might contain uncommitted rows, please consider reopening the channel to restart.
                at org.apache.flink.shaded.net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestChannelInternal.checkValidation(SnowflakeStreamingIngestChannelInternal.java:462)
                at org.apache.flink.shaded.net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestChannelInternal.close(SnowflakeStreamingIngestChannelInternal.java:273)
                at io.deltastream.flink.connector.snowflake.sink.internal.SnowflakeSinkServiceImpl.close(SnowflakeSinkServiceImpl.java:245)
                at org.apache.flink.util.IOUtils.closeAll(IOUtils.java:255)
                at org.apache.flink.util.IOUtils.closeAll(IOUtils.java:234)
                at org.apache.flink.util.IOUtils.closeAll(IOUtils.java:223)
                at io.deltastream.flink.connector.snowflake.sink.SnowflakeSinkWriter.close(SnowflakeSinkWriter.java:144)
                at org.apache.flink.util.IOUtils.closeAll(IOUtils.java:255)
                at org.apache.flink.util.IOUtils.closeAll(IOUtils.java:234)
                at org.apache.flink.util.IOUtils.closeAll(IOUtils.java:223)
                at org.apache.flink.streaming.runtime.operators.sink.SinkWriterOperator.close(SinkWriterOperator.java:219)
                at org.apache.flink.streaming.runtime.tasks.StreamOperatorWrapper.close(StreamOperatorWrapper.java:163)
                at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.closeAllOperators(RegularOperatorChain.java:125)
                at org.apache.flink.streaming.runtime.tasks.StreamTask.closeAllOperators(StreamTask.java:1113)
                at org.apache.flink.util.IOUtils.closeAll(IOUtils.java:255)
                at org.apache.flink.core.fs.AutoCloseableRegistry.doClose(AutoCloseableRegistry.java:72)
                at org.apache.flink.util.AbstractAutoCloseableRegistry.close(AbstractAutoCloseableRegistry.java:127)
                at org.apache.flink.streaming.runtime.tasks.StreamTask.cleanUp(StreamTask.java:1021)
                at org.apache.flink.runtime.taskmanager.Task.lambda$restoreAndInvoke$0(Task.java:942)
                at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:960)
                at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:942)
                ... 3 more
Caused by: org.apache.flink.shaded.net.snowflake.ingest.utils.SFException: Channel SNOWFLAKE SINK_12 is invalid and might contain uncommitted rows, please consider reopening the channel to restart.
        at org.apache.flink.shaded.net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestChannelInternal.checkValidation(SnowflakeStreamingIngestChannelInternal.java:462)
        at org.apache.flink.shaded.net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestChannelInternal.insertRows(SnowflakeStreamingIngestChannelInternal.java:349)
        at org.apache.flink.shaded.net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestChannelInternal.insertRow(SnowflakeStreamingIngestChannelInternal.java:328)
        at io.deltastream.flink.connector.snowflake.sink.internal.SnowflakeSinkServiceImpl.lambda$insertRowWithFallback$4(SnowflakeSinkServiceImpl.java:313)
        at org.apache.flink.shaded.dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
        at org.apache.flink.shaded.dev.failsafe.Functions.lambda$get$0(Functions.java:46)
        at org.apache.flink.shaded.dev.failsafe.internal.FallbackExecutor.lambda$apply$0(FallbackExecutor.java:51)
        ... 20 more`

Thanks in advance.

**Comment by vinclv** [comment]
I noticed that for issues like above, you had a TODO to reopen the channel like below

```
        // wait for flush, unless the result wasn't a future
        if (flushRes instanceof CompletableFuture) {
            try {
                ((CompletableFuture<?>) flushRes).get();
                LOGGER.info("Successfully flushed channel '{}'", this.getChannelName());
            } catch (InterruptedException | ExecutionException e) {
                // TODO reopen channel:
                // https://github.com/deltastreaminc/flink-connector-snowflake/issues/11
                LOGGER.warn(
                        "Snowflake channel flush did not finish successfully;"
                                + "Flush will happen within the next buffer time of {}ms",
                        this.getWriterConfig().getMaxBufferTimeMs());
            }
        } else {
            // TODO reopen channel:
            // https://github.com/deltastreaminc/flink-connector-snowflake/issues/11
            LOGGER.warn(
                    "Snowflake channel flush did not return a handle to wait on: got {};"
                            + "Flush will happen within the next buffer time of {}ms",
                    flushRes.getClass().getSimpleName(),
                    this.getWriterConfig().getMaxBufferTimeMs());
        }
    }
```

However, in the new releases, you have taken a different approach to retry failed checkpoint rather than reopen the channel. Do you think upgrading to this will fix the above issue? Because, with above issue, I found duplicates going into Snowflake.

Thanks again.

**Comment by ini-span** [comment]
I'm also seeing similar issues to this bug:

```
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at org.apache.flink.shaded.net.snowflake.client.jdbc.internal.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:45)
at org.apache.flink.shaded.net.snowflake.client.jdbc.internal.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:115)
at org.apache.flink.shaded.net.snowflake.client.jdbc.internal.amazonaws.services.s3.transfer.internal.UploadCallable.call(UploadCallable.java:149)
at org.apache.flink.shaded.net.snowflake.client.jdbc.internal.amazonaws.services.s3.transfer.internal.UploadCallable.uploadInOneChunk(UploadCallable.java:169)
at org.apache.flink.shaded.net.snowflake.client.jdbc.internal.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1851)
at org.apache.flink.shaded.net.snowflake.client.jdbc.internal.amazonaws.services.s3.AmazonS3Client.uploadObject(AmazonS3Client.java:1891)
at org.apache.flink.shaded.net.snowflake.client.jdbc.internal.amazonaws.services.s3.AmazonS3Client$PutObjectStrategy.invokeServiceCall(AmazonS3Client.java:6600)
at org.apache.flink.shaded.net.snowflake.client.jdbc.internal.amazonaws.services.s3.AmazonS3Client.access$300(AmazonS3Client.java:422)
at org.apache.flink.shaded.net.snowflake.client.jdbc.internal.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5466)
at org.apache.flink.shaded.net.snowflake.client.jdbc.internal.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5519)
at org.apache.flink.shaded.net.snowflake.client.jdbc.internal.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
at org.apache.flink.shaded.net.snowflake.client.jdbc.internal.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
at org.apache.flink.shaded.net.snowflake.client.jdbc.internal.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
at org.apache.flink.shaded.net.snowflake.client.jdbc.internal.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
at org.apache.flink.shaded.net.snowflake.client.jdbc.internal.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
at org.apache.flink.shaded.net.snowflake.client.jdbc.internal.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
at org.apache.flink.shaded.net.snowflake.client.jdbc.internal.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
at org.apache.flink.shaded.net.snowflake.client.jdbc.internal.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
at org.apache.flink.shaded.net.snowflake.client.jdbc.internal.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387)
at org.apache.flink.shaded.net.snowflake.client.jdbc.internal.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418)
at org.apache.flink.shaded.net.snowflake.client.jdbc.internal.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879)
Caused by: org.apache.flink.shaded.net.snowflake.client.jdbc.internal.amazonaws.services.s3.model.AmazonS3Exception: The provided token has expired. (Service: Amazon S3; Status Code: 400; Error Code: ExpiredToken)
at java.base/java.lang.Thread.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
at org.apache.flink.shaded.net.snowflake.ingest.streaming.internal.FlushService.lambda$distributeFlushTasks$12(FlushService.java:502)
at org.apache.flink.shaded.net.snowflake.ingest.streaming.internal.FlushService.buildAndUpload(FlushService.java:608)
at org.apache.flink.shaded.net.snowflake.ingest.streaming.internal.FlushService.upload(FlushService.java:637)
at org.apache.flink.shaded.net.snowflake.ingest.streaming.internal.InternalStage.put(InternalStage.java:309)
at org.apache.flink.shaded.net.snowflake.ingest.streaming.internal.InternalStage.putRemote(InternalStage.java:150)
at org.apache.flink.shaded.net.snowflake.client.jdbc.SnowflakeFileTransferAgent.uploadWithoutConnection(SnowflakeFileTransferAgent.java:2245)
at org.apache.flink.shaded.net.snowflake.client.jdbc.SnowflakeFileTransferAgent.pushFileToRemoteStore(SnowflakeFileTransferAgent.java:2126)
at org.apache.flink.shaded.net.snowflake.client.jdbc.cloud.storage.SnowflakeS3Client.upload(SnowflakeS3Client.java:664)
at org.apache.flink.shaded.net.snowflake.client.jdbc.cloud.storage.SnowflakeS3Client.handleS3Exception(SnowflakeS3Client.java:858)
org.apache.flink.shaded.net.snowflake.client.jdbc.SnowflakeSQLLoggedException: S3 operation failed: Operation=upload, Error type=Client, Error code=ExpiredToken, Error message=The provided token has expired. (Service: Amazon S3; Status Code: 400; Error Code: ExpiredToken)
upload
```

Looking to play around with building a custom connector using Snowflake Streaming. Let me know if there is a better option!

Thank you!
